# Generated by Django 6.0.4 on 2026-04-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(default=list)),
                ('extracted_params', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI чат сессия',
                'verbose_name_plural': 'AI чат сессии',
                'db_table': 'ai_chat_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('search_count', models.PositiveIntegerField(default=1)),
                ('last_searched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'История поиска',
                'verbose_name_plural': 'История поиска',
                'db_table': 'search_history',
                'ordering': ['-search_count'],
            },
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'История просмотров',
                'verbose_name_plural': 'История просмотров',
                'db_table': 'view_history',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
